scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['my-service:8000']
        labels:
          service: 'my-service'
          group: 'production'
